### ISSUE TITLE
Dropdown multilingual corrections

### ISSUE THREAD

**Issue by smile-eh** [DIS-SIN/CORTEX#40]
Evalhalla drop downs currentloy only support one language, meaning options have to have both (Example "Yes / Oui")

**Comment by mightyweasel** [comment]
Fixed in the v2-lib-refactor branch of Evalhalla. Catching the en/fr options as they roll in from the interpreter and storing them for use in the dynamic language change. 

- Removes bug: Both languages display in the select box at once. Unanimous dislike of 'feature'.
- Adds bug: If an answer has been selected in the dropdown, it is cleared on language change

Closing this one as the core requirement is fixed, and once move to the React version of the player this will be a non-issue
